# Generated by Django 5.1.4 on 2024-12-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="role",
        ),
        migrations.AlterField(
            model_name="ride",
            name="customer_name",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="ride.user"
            ),
        ),
    ]
