# Generated by Django 5.1.4 on 2024-12-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride", "0002_remove_ride_role_alter_ride_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="customer_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ride.user"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="driver_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
